### ISSUE TITLE
5.0.0 Roadmap of Ideas

### ISSUE THREAD

**Issue by thecoder75** [thecoder75/liveme-tools#43]
The following are currently being planned for the 5.0.0 release.

Added:
- [x] Ability to add a single URL manually to the download manager.
- [x] Ability to limit the initial number of replay results (10,25,50,unlimited).
- [x] Show Video IDs now on each video entry for easier sharing online.
users. 
- [x] Import a list of VideoIDs.
- [x] Export a list of UserID(Favorites) list.
- [x] Ability to search by hashtags in the video title.
- [x] **IMPORTANT** Move modules to main and set up IPC communications to fix module issues.

**Comment by polydragon** [comment]
- [ ] Idea: Hold off on loading more replays/users/followers/fans until user has scrolled to the bottom or at least 75% of the page.
- [ ] Idea: Bulk import/export of UserIDs/VideoIDs/favourite list.

**Comment by thecoder75** [comment]
Updated entry 2 in the list to set initial number of replays loaded and load more when the user scrolls.

**Comment by thecoder75** [comment]
Updated, added entry to the list above.

**Comment by polydragon** [comment]
Maybe we could add a checkbox on the video list for each video entry, then add two buttons somewhere. "Export IDs" and "Download all."

And if you're changing the design to a new style, could it be a good idea to use an already existing CSS framework. So we won't have to style everything ourselves and everything will look consistent.

**Comment by thecoder75** [comment]
Yes, was thinking/hoping to use an existing css framework.  I know of too many and most are either adding BIG buttons and stuff or complex to incorporate.

Not sure about the checkbox.  Most people first play a video to verify if its worth downloading.  Very very few if any just blind download a bunch.

**Comment by thecoder75** [comment]
I originally took the TopCoat CSS Framework and modified it a bit and added to it to create what is being used now.

**Comment by polydragon** [comment]
Ah okay, I see. I didn't look into the styles a lot so wasn't sure if it was all custom. I do most of my webapps in Angular these days, so I'm not sure of any plain CSS frameworks that we could use. Maybe just what we have now but modified a little - I'm not sure what your plans are.

**Comment by thecoder75** [comment]
Guess we could look at Angular and see what stylings there are out there.  Most of what I was thinking of originally doing was removing shadows and 3D-like look from controls and adapting a more flat UI look with maybe some different colors.

**Comment by thecoder75** [comment]
Decided to not mess with the UI for now, it may be a future thing.  Just want to get a few updates done and push the release out after testing.

**Comment by polydragon** [comment]
Yeah, if we went with something like Angular. While it would make future coding a hell of a lot easier as it would handle refreshing the view for us when our data changes (no more manually pushing updates to it ourselves), there would be a lot of work involved in rewriting what we already have.

**Comment by thecoder75** [comment]
Another worry of mine would be how much code or javascript code is being added into the project that might cause conflicts or errors later on?

Also Angular adds support for browsers that we don't need in our project as we're using only Chromium/Webkit and can get rid of a lot of crap support stuff needed.  If I could get a stripped down version of jQuery to use that only support Chromium/Webkit I would switch to using that version instead of the one I'm using now.

**Comment by polydragon** [comment]
To be honest I think you're worrying about the wrong things. I would rather use something that's been tried and tested and is used by a lot of other developers, rather than slicing up a framework just to save a few kb. The developers of the frameworks will not be offering the sliced up versions, so it would be up to you or someone else - and I'm sure that would cause a lot more issues and frustrations than just using the default offering. The things we add are more likely to contain bugs.
